server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Angular SPA: enrutar todo a index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache agresivo para assets con hashing (Angular outputHashing: all)
  location ~* \.(?:css|js|mjs|map|json|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
